In [ ]:
print("Hello, World!")

In [1]:
import matplotlib.pyplot as plt
from sklearn_genetic import GAFeatureSelectionCV
from sklearn_genetic.plots import plot_fitness_evolution
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

/opt/anaconda3/envs/thesis_experiments_TEST/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [13]:
data = load_iris()
print(type(data))   
X, y = data["data"], data["target"]

print(X)

noise = np.random.uniform(0, 10, size=(X.shape[0], 10))

X = np.hstack((X, noise))
X.shape

<class 'sklearn.utils._bunch.Bunch'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7

(150, 14)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [4]:
clf = SVC(gamma='auto')

evolved_estimator = GAFeatureSelectionCV(
    estimator=clf,
    cv=3,
    scoring="accuracy",
    population_size=30,
    generations=20,
    n_jobs=-1,
    verbose=True,
    keep_top_k=2,
    elitism=True,
)

In [9]:
evolved_estimator.fit(X, y)
features = evolved_estimator.support_

# Predict only with the subset of selected features
y_predict_ga = evolved_estimator.predict(X_test)
print(y_predict_ga)



accuracy = accuracy_score(y_test, y_predict_ga)


gen	nevals	fitness 	fitness_std	fitness_max	fitness_min
0  	30    	0.592444	0.123705   	0.793333   	0.333333   
1  	60    	0.664222	0.0965706  	0.853333   	0.506667   
2  	60    	0.700444	0.113097   	0.833333   	0.426667   
3  	60    	0.674444	0.161998   	0.913333   	0.4        
4  	60    	0.727333	0.136315   	0.913333   	0.433333   
5  	60    	0.779111	0.119042   	0.913333   	0.433333   
6  	60    	0.803556	0.13608    	0.913333   	0.42       
7  	60    	0.816667	0.148711   	0.913333   	0.38       
8  	60    	0.871778	0.0964816  	0.953333   	0.553333   
9  	60    	0.778222	0.184792   	0.953333   	0.42       
10 	60    	0.784667	0.153885   	0.953333   	0.473333   
11 	60    	0.844667	0.126118   	0.953333   	0.48       
12 	60    	0.790222	0.198294   	0.953333   	0.4        
13 	60    	0.797111	0.185988   	0.953333   	0.386667   
14 	60    	0.826222	0.145663   	0.953333   	0.446667   
15 	60    	0.833333	0.151838   	0.966667   	0.426667   
16 	60    	0.800222	0.206985   	0.973333   	0.42

In [6]:
#Best features found
print(evolved_estimator.support_)
print("accuracy score: ", "{:.2f}".format(accuracy))

[False False  True  True False False False False False False False False
 False False]
accuracy score:  0.96
